### ISSUE TITLE
Tracking issue for backend tasks

### ISSUE THREAD

**Issue by kiancross** [kiancross/unifed#145]
- [x] Sort out dependency injection for `internal-server`.
- [x] Sort out `internal-server` testing.
- [x] Put all tests in a single job
