### ISSUE TITLE
Tracking issue for frontend tidy up tasks

### ISSUE THREAD

**Issue by kiancross** [kiancross/unifed#155]
- [x] Fix client side state (login/logout).
- [ ] Move routes to their own definitions and use nested routes.
- [ ] Find out how to test routes.
- [x] `PostEditor` and `CommentEditor` are very similar - they should be unified.
- [ ] Stop using things like `window.redirect` and `window.assign`. Dynamically update content instead.
